# -*- coding: utf-8 -*-
"""meowLS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bc7GAqq50ZsW_8zQQ8PNje1wJoIodFcS
"""
import time
from Features.WikiFrequency import *
from Features.Ngram import *
start = time.time()
dic = pyphen.Pyphen(lang='en')


"""**lexicon**"""
class Initializer:
    def __init__(self):
        lexicons = {}
        with open(DIRECTORY + "/lexicon.tsv") as f:
            for line in f:
                (key, val) = line.split()
                lexicons[key.lower()] = val
        self.substitutions_db = load_obj(DIRECTORY + "substitutions")
        self.fivegram_model = NgramModel(DIRECTORY + "newsela.lm", 2, 2)
        self.threegram_model = NgramModel(DIRECTORY + "newsela.lm", 1, 1)
        self.syllable_dict = pyphen.Pyphen(lang='en')
        # Load the subs ranking file
        self.subs_rank_nnclf = load_obj(DIRECTORY + 'subs_ranking_model_3')
        self.wiki_frequency = WikiFrequency()
        elapsed_time = time.time() - start
        print("loaded models in ", elapsed_time)



"""**Model**"""

from sklearn.preprocessing import maxabs_scale
import re

